import { prisma } from "@/lib/prisma";
import { assertSameOrigin, jsonError, requireUser, requestIdempotencyKey } from "@/lib/auth";
import { isFinanceConflict, serializableTransaction } from "@/lib/finance-transaction";

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params; assertSameOrigin(request); const user = await requireUser(["ADMIN", "FINANCE"]); const key = requestIdempotencyKey(request); if (!key) return Response.json({ error: "Idempotency-Key wajib diisi" }, { status: 400 }); const operation = `PAYMENT_CREATE:${id}`; const body = await request.json().catch(() => ({})); const amount = Number(body.amount); const paidAt = new Date(body.paidAt); const method = ["TRANSFER", "CASH", "OTHER"].includes(body.method) ? body.method : "OTHER"; if (!Number.isSafeInteger(amount) || amount <= 0 || Number.isNaN(paidAt.getTime())) return Response.json({ error: "Nominal dan tanggal pembayaran tidak valid" }, { status: 400 });
    const result = await prisma.$transaction(async (tx) => { const duplicate = await tx.mutationRequest.findUnique({ where: { key } }); if (duplicate && (duplicate.userId !== user.id || duplicate.operation !== operation)) throw new Error("IDEMPOTENCY_CONFLICT"); if (duplicate?.response) return duplicate.response as unknown as { id: string; balance: number }; const invoice = await tx.invoice.findUnique({ where: { id }, include: { payments: { where: { status: "VALID" }, select: { amount: true } } } }); if (!invoice) throw new Error("NOT_FOUND"); if (invoice.status !== "ISSUED") throw new Error("NOT_ISSUED"); if (paidAt < invoice.issueDate || paidAt > new Date()) throw new Error("INVALID_DATE"); const paid = invoice.payments.reduce((sum, payment) => sum + payment.amount, 0); const balance = invoice.totalAmount - paid; if (amount > balance) throw new Error("OVERPAYMENT"); const payment = await tx.payment.create({ data: { invoiceId: invoice.id, recordedById: user.id, paidAt, amount, method } }); const nextBalance = balance - amount; await tx.auditLog.create({ data: { actorId: user.id, action: "PAYMENT_RECORDED", objectType: "Payment", objectId: payment.id, changes: { invoiceId: invoice.id, amount, nextBalance } } }); const response = { id: payment.id, balance: nextBalance }; await tx.mutationRequest.create({ data: { key, userId: user.id, operation, response } }); return response; }, serializableTransaction); return Response.json({ payment: result });
  } catch (error) { if (isFinanceConflict(error)) return Response.json({ error: "Data keuangan berubah bersamaan. Muat ulang lalu coba lagi." }, { status: 409 }); if (error instanceof Error && error.message === "NOT_FOUND") return Response.json({ error: "Invoice tidak ditemukan" }, { status: 404 }); if (error instanceof Error && error.message === "NOT_ISSUED") return Response.json({ error: "Pembayaran hanya dapat dicatat pada invoice terbit" }, { status: 409 }); if (error instanceof Error && error.message === "INVALID_DATE") return Response.json({ error: "Tanggal pembayaran harus berada antara tanggal terbit dan hari ini" }, { status: 400 }); if (error instanceof Error && error.message === "OVERPAYMENT") return Response.json({ error: "Nominal melebihi saldo invoice" }, { status: 409 }); if (error instanceof Error && error.message === "IDEMPOTENCY_CONFLICT") return Response.json({ error: "Idempotency-Key sudah dipakai untuk permintaan lain" }, { status: 409 }); return jsonError(error); }
}
