import { prisma } from "@/lib/prisma";
import { assertSameOrigin, jsonError, requireUser, requestIdempotencyKey } from "@/lib/auth";

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params; assertSameOrigin(request); const user = await requireUser(["ADMIN", "FINANCE"]); const key = requestIdempotencyKey(request); if (!key) return Response.json({ error: "Idempotency-Key wajib diisi" }, { status: 400 }); const year = new Date().getFullYear();
    const invoice = await prisma.$transaction(async (tx) => { const duplicate = await tx.mutationRequest.findUnique({ where: { key } }); if (duplicate && duplicate.userId !== user.id) throw new Error("IDEMPOTENCY_CONFLICT"); if (duplicate?.response) return duplicate.response as unknown as { id: string; invoiceNumber: string; status: string }; const current = await tx.invoice.findUnique({ where: { id }, include: { items: true } }); if (!current) throw new Error("NOT_FOUND"); if (current.status !== "DRAFT") throw new Error("NOT_DRAFT"); if (current.approvalStatus !== "APPROVED") throw new Error("NOT_APPROVED"); if (current.totalAmount <= 0 || current.items.length === 0) throw new Error("INVALID_INVOICE"); const sequence = await tx.invoiceSequence.upsert({ where: { year }, create: { year, nextNumber: 2 }, update: { nextNumber: { increment: 1 } } }); const number = `SD/${year}/${String(sequence.nextNumber - 1).padStart(4, "0")}`; const issued = await tx.invoice.update({ where: { id }, data: { status: "ISSUED", invoiceNumber: number, issuedAt: new Date() } }); await tx.auditLog.create({ data: { actorId: user.id, action: "INVOICE_ISSUED", objectType: "Invoice", objectId: id, changes: { invoiceNumber: number } } }); const response = { id: issued.id, invoiceNumber: number, status: issued.status }; await tx.mutationRequest.create({ data: { key, userId: user.id, operation: "INVOICE_ISSUE", response } }); return response; }); return Response.json({ invoice });
  } catch (error) { if (error instanceof Error && error.message === "NOT_FOUND") return Response.json({ error: "Invoice tidak ditemukan" }, { status: 404 }); if (error instanceof Error && error.message === "NOT_DRAFT") return Response.json({ error: "Invoice sudah diterbitkan atau dibatalkan" }, { status: 409 }); if (error instanceof Error && error.message === "NOT_APPROVED") return Response.json({ error: "Invoice harus disetujui sebelum diterbitkan" }, { status: 409 }); if (error instanceof Error && error.message === "INVALID_INVOICE") return Response.json({ error: "Invoice harus memiliki item dan total positif" }, { status: 400 }); if (error instanceof Error && error.message === "IDEMPOTENCY_CONFLICT") return Response.json({ error: "Idempotency-Key sudah dipakai oleh actor lain" }, { status: 409 }); return jsonError(error); }
}
