"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/purity */

import Link from "next/link";
import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { apiFetch, ApiError, formatDate } from "@/lib/api-client";
import { Badge, EmptyState, FormField, Icon, PageHeader, SearchField, inputClass } from "@/components/ops-ui";

type TaskStatus = "TODO" | "IN_PROGRESS" | "BLOCKED" | "DONE" | "CANCELLED";
type TaskPriority = "LOW" | "MEDIUM" | "HIGH" | "URGENT";
type Task = { id: string; programId: string; assigneeId: string; title: string; description: string | null; status: TaskStatus; priority: TaskPriority; dueDate: string; blockedReason: string | null; completionNote: string | null; version: number; program: { id: string; name: string; client: { id: string; businessName: string } }; assignee: { id: string; name: string }; checklist: { id: string; label: string; isDone: boolean }[] };
type ProgramOption = { id: string; name: string; client: { businessName: string }; status: string };
const columns: { status: TaskStatus; label: string }[] = [{ status: "TODO", label: "Belum mulai" }, { status: "IN_PROGRESS", label: "Sedang dikerjakan" }, { status: "BLOCKED", label: "Terblokir" }, { status: "DONE", label: "Selesai" }];
const priorityTone: Record<TaskPriority, "sage" | "terracotta" | "amber" | "slate" | "red"> = { LOW: "slate", MEDIUM: "amber", HIGH: "terracotta", URGENT: "red" };

export default function TasksPage() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [programs, setPrograms] = useState<ProgramOption[]>([]);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [mutationError, setMutationError] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [saving, setSaving] = useState(false);
  const movingIds = useRef(new Set<string>());
  const [movingTaskIds, setMovingTaskIds] = useState<string[]>([]);

  const load = () => { setLoading(true); setError(""); Promise.all([apiFetch<{ tasks: Task[] }>("/api/tasks"), apiFetch<{ programs: ProgramOption[] }>("/api/programs")]).then(([taskPayload, programPayload]) => { setTasks(taskPayload.tasks); setPrograms(programPayload.programs.filter((program) => !["COMPLETED", "CANCELLED"].includes(program.status))); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Pekerjaan gagal dimuat")).finally(() => setLoading(false)); };
  useEffect(load, []);
  const filtered = useMemo(() => tasks.filter((task) => [task.title, task.program.name, task.program.client.businessName, task.assignee.name].join(" ").toLowerCase().includes(query.toLowerCase())), [tasks, query]);

  async function move(task: Task, status: TaskStatus) {
    if (status === task.status || movingIds.current.has(task.id)) return;
    const note = status === "BLOCKED" ? window.prompt("Mengapa pekerjaan terblokir?", task.blockedReason ?? "") : status === "DONE" ? window.prompt("Ringkasan hasil pekerjaan?", task.completionNote ?? "") : null;
    if ((status === "BLOCKED" || status === "DONE") && !note?.trim()) return;
    movingIds.current.add(task.id); setMovingTaskIds((current) => [...current, task.id]); setMutationError(""); setTasks((current) => current.map((item) => item.id === task.id ? { ...item, status, version: item.version + 1, blockedReason: status === "BLOCKED" ? note : item.blockedReason, completionNote: status === "DONE" ? note : item.completionNote } : item));
    try { const payload = await apiFetch<{ task: Task }>(`/api/tasks/${task.id}`, { method: "PATCH", body: JSON.stringify({ status, version: task.version, ...(status === "BLOCKED" ? { blockedReason: note } : {}), ...(status === "DONE" ? { completionNote: note } : {}) }) }); setTasks((current) => current.map((item) => item.id === task.id ? payload.task : item)); } catch (cause) { setTasks((current) => current.map((item) => item.id === task.id ? task : item)); setMutationError(cause instanceof ApiError ? cause.message : "Status task gagal disimpan"); } finally { movingIds.current.delete(task.id); setMovingTaskIds((current) => current.filter((id) => id !== task.id)); }
  }

  async function createTask(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setMutationError(""); const form = new FormData(event.currentTarget);
    try { const payload = await apiFetch<{ task: Task }>("/api/tasks", { method: "POST", body: JSON.stringify({ programId: form.get("programId"), title: form.get("title"), description: form.get("description"), priority: form.get("priority"), dueDate: form.get("dueDate") }) }); setTasks((current) => [...current, payload.task].sort((a, b) => new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime())); setShowForm(false); } catch (cause) { setMutationError(cause instanceof ApiError ? cause.message : "Pekerjaan gagal disimpan"); } finally { setSaving(false); }
  }

  return <div className="ops-page page-enter"><PageHeader eyebrow="Ritme kerja tim" title="Pekerjaan" description="Status, deadline, dan perubahan pekerjaan tersimpan ke server dengan scope sesuai role." action={() => { setMutationError(""); setShowForm(true); }} actionLabel="Tambah pekerjaan" />
    {mutationError && <div className="mt-5 rounded-xl bg-[#fae9e7] p-3 text-xs font-medium text-[#a5423a]" role="alert">{mutationError}</div>}
    <section className="surface mt-6 p-4 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><SearchField value={query} onChange={setQuery} placeholder="Cari pekerjaan, client, program, atau assignee…" /><span className="text-xs text-[var(--muted)]">{filtered.length} pekerjaan terlihat</span></div>{loading ? <div className="grid min-h-[320px] place-items-center"><p className="text-sm text-[var(--muted)]">Memuat pekerjaan…</p></div> : error ? <div className="mt-5"><EmptyState icon="checkSquare" title="Pekerjaan gagal dimuat" description={error} actionLabel="Coba lagi" onAction={load} /></div> : filtered.length === 0 ? <div className="mt-5"><EmptyState icon="checkSquare" title="Belum ada pekerjaan" description="Task sesuai akses akun akan muncul setelah dibuat dari program." actionLabel="Tambah pekerjaan" onAction={() => setShowForm(true)} /></div> : <div className="mt-5 grid gap-4 xl:grid-cols-4">{columns.map((column) => { const rows = filtered.filter((task) => task.status === column.status); return <section className="min-w-0 rounded-2xl bg-[#f7f9f6] p-3" key={column.status}><div className="flex items-center justify-between px-1 pb-3"><h2 className="text-xs font-semibold uppercase tracking-[0.1em] text-[#526055]">{column.label}</h2><span className="grid h-6 min-w-6 place-items-center rounded-full bg-white px-1.5 text-[11px] font-semibold text-[#738b69]">{rows.length}</span></div><div className="grid gap-3">{rows.length === 0 ? <p className="rounded-xl border border-dashed border-[#d6ded3] p-4 text-center text-xs text-[var(--muted)]">Kosong</p> : rows.map((task) => <article className="rounded-xl border border-[var(--border)] bg-white p-4 shadow-[0_3px_10px_rgba(35,57,38,0.03)]" key={task.id}><div className="flex items-start justify-between gap-2"><Badge tone={priorityTone[task.priority]}>{task.priority}</Badge><span className="text-[11px] text-[var(--muted)]">{formatDate(task.dueDate)}</span></div><Link href={`/dashboard/tasks/${task.id}`} className="mt-3 block"><h3 className="line-clamp-2 text-sm font-semibold text-[#334035] hover:text-[#506545]">{task.title}</h3><p className="mt-1 line-clamp-1 text-xs text-[var(--muted)]">{task.program.client.businessName} · {task.program.name}</p></Link><div className="mt-3 flex items-center justify-between gap-2 border-t border-[var(--border)] pt-3"><span className="truncate text-xs text-[var(--muted)]">{task.assignee.name}</span><select className="h-8 rounded-lg border border-[var(--border)] bg-[#fbfcfa] px-2 text-[11px] text-[#526055]" aria-label={`Pindahkan ${task.title}`} disabled={movingTaskIds.includes(task.id)} value={task.status} onChange={(event) => move(task, event.target.value as TaskStatus)}><option value="TODO">Belum mulai</option><option value="IN_PROGRESS">Dikerjakan</option><option value="BLOCKED">Terblokir</option><option value="DONE">Selesai</option></select></div></article>)}</div></section>; })}</div>}</section>
    {showForm && <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-[#283529]/30 p-4 backdrop-blur-[2px]" role="dialog" aria-modal="true"><div className="my-8 w-full max-w-lg rounded-2xl border border-[var(--border)] bg-white p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between"><div><p className="eyebrow">Pekerjaan baru</p><h2 className="mt-1 text-xl font-semibold tracking-[-0.03em] text-[#334035]">Tambah ke program</h2></div><button type="button" onClick={() => setShowForm(false)} className="grid h-9 w-9 place-items-center rounded-lg text-[var(--muted)] hover:bg-[#f0f2f0]" aria-label="Tutup">×</button></div><form className="mt-6 grid gap-4" onSubmit={createTask}><FormField label="Program"><select name="programId" className={inputClass} required defaultValue=""><option value="" disabled>Pilih program</option>{programs.map((program) => <option key={program.id} value={program.id}>{program.client.businessName} · {program.name}</option>)}</select></FormField><FormField label="Judul pekerjaan"><input name="title" className={inputClass} required maxLength={240} placeholder="Contoh: Validasi alur kas" /></FormField><FormField label="Deskripsi"><textarea name="description" className="min-h-20 w-full rounded-xl border border-[var(--border)] bg-[#fbfcfa] p-3 text-sm outline-none focus:border-[#738b69] focus:ring-2 focus:ring-[#738b69]/15" maxLength={5000} placeholder="Konteks dan hasil yang diharapkan" /></FormField><div className="grid gap-4 sm:grid-cols-2"><FormField label="Prioritas"><select name="priority" className={inputClass} defaultValue="MEDIUM"><option value="LOW">Rendah</option><option value="MEDIUM">Sedang</option><option value="HIGH">Tinggi</option><option value="URGENT">Urgent</option></select></FormField><FormField label="Deadline"><input name="dueDate" type="date" className={inputClass} required defaultValue={new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10)} /></FormField></div><p className="text-xs leading-5 text-[var(--muted)]">Pekerjaan baru ditugaskan ke akun Anda. Pastikan akun Anda anggota aktif program.</p><div className="mt-2 flex justify-end gap-2"><button type="button" onClick={() => setShowForm(false)} className="min-h-11 rounded-xl px-4 text-sm font-semibold text-[var(--muted)] hover:bg-[#f0f2f0]">Batal</button><button disabled={saving || programs.length === 0} type="submit" className="min-h-11 rounded-xl bg-[#bf6d4e] px-4 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-60">{saving ? "Menyimpan…" : "Simpan pekerjaan"}</button></div></form></div></div>}
  </div>;
}
