import { prisma } from "@/lib/prisma";
import { assertSameOrigin, jsonError, requireUser } from "@/lib/auth";

function parseLine(line: string) { const cells: string[] = []; let cell = ""; let quoted = false; for (let index = 0; index < line.length; index += 1) { const char = line[index]; if (char === '"' && line[index + 1] === '"') { cell += '"'; index += 1; } else if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { cells.push(cell.trim()); cell = ""; } else cell += char; } cells.push(cell.trim()); return cells; }

export async function POST(request: Request) {
  try {
    assertSameOrigin(request); const user = await requireUser(["ADMIN"]); const form = await request.formData(); const file = form.get("file"); if (!(file instanceof File) || file.size > 2 * 1024 * 1024) return Response.json({ error: "CSV wajib diisi dan maksimal 2 MB" }, { status: 400 });
    const lines = (await file.text()).split(/\r?\n/).filter(Boolean); if (lines.length < 2 || lines.length > 201) return Response.json({ error: "CSV harus berisi 1 header dan maksimal 200 baris" }, { status: 400 }); const headers = parseLine(lines[0]).map((header) => header.toLowerCase()); const required = ["businessname", "contactname"]; if (!required.every((name) => headers.includes(name))) return Response.json({ error: "Header wajib: businessName, contactName" }, { status: 400 });
    const index = (name: string) => headers.indexOf(name.toLowerCase()); const created: string[] = [];
    await prisma.$transaction(async (tx) => { for (const line of lines.slice(1)) { const values = parseLine(line); const businessName = values[index("businessName")]?.slice(0, 160); const contactName = values[index("contactName")]?.slice(0, 160); if (!businessName || !contactName) throw new Error("INVALID_ROW"); const leadId = values[index("leadId")] || null; if (leadId && !(await tx.user.findFirst({ where: { id: leadId, role: "LEAD", status: "ACTIVE" } }))) throw new Error("INVALID_LEAD"); const client = await tx.client.create({ data: { businessName, sector: values[index("sector")]?.slice(0, 120) || null, address: values[index("address")]?.slice(0, 300) || null, leadId, contacts: { create: { name: contactName, email: values[index("contactEmail")]?.toLowerCase().slice(0, 160) || null, phone: values[index("contactPhone")]?.slice(0, 40) || null, isPrimary: true } } } }); created.push(client.id); await tx.auditLog.create({ data: { actorId: user.id, action: "CLIENT_IMPORTED", objectType: "Client", objectId: client.id, changes: { source: "csv" } } }); } });
    return Response.json({ imported: created.length, clientIds: created }, { status: 201 });
  } catch (error) { if (error instanceof Error && error.message === "INVALID_ROW") return Response.json({ error: "Ada baris CSV yang nama usaha atau kontaknya kosong" }, { status: 400 }); if (error instanceof Error && error.message === "INVALID_LEAD") return Response.json({ error: "leadId pada CSV tidak valid" }, { status: 400 }); return jsonError(error); }
}
