"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { apiFetch, ApiError, formatDate } from "@/lib/api-client";
import { EmptyState, FormField, Icon, PageHeader, SearchField, inputClass, Badge } from "@/components/ops-ui";

type Contact = { id: string; name: string; title: string | null; email: string | null; phone: string | null; isPrimary: boolean };
type Client = { id: string; businessName: string; sector: string | null; address: string | null; status: "PROSPECT" | "ACTIVE" | "INACTIVE" | "ARCHIVED"; leadId: string | null; contacts: Contact[]; programs: { id: string; name: string; status: string; targetDate: string }[]; updatedAt: string };
const labels: Record<Client["status"], string> = { ACTIVE: "Aktif", PROSPECT: "Prospek", INACTIVE: "Tidak aktif", ARCHIVED: "Arsip" };
const tone: Record<Client["status"], "sage" | "terracotta" | "amber" | "slate"> = { ACTIVE: "sage", PROSPECT: "amber", INACTIVE: "slate", ARCHIVED: "slate" };

export default function ClientsPage() {
  const [clients, setClients] = useState<Client[]>([]);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<"Semua" | Client["status"]>("Semua");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [saving, setSaving] = useState(false);
  const [formError, setFormError] = useState("");

  const load = () => { setLoading(true); setError(""); apiFetch<{ clients: Client[] }>("/api/clients").then((payload) => setClients(payload.clients)).catch((cause) => setError(cause instanceof Error ? cause.message : "Client gagal dimuat")).finally(() => setLoading(false)); };
  useEffect(load, []);
  const filtered = useMemo(() => clients.filter((client) => (status === "Semua" || client.status === status) && [client.businessName, client.sector ?? "", client.contacts[0]?.name ?? ""].join(" ").toLowerCase().includes(query.toLowerCase())), [clients, query, status]);

  async function createClient(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setFormError(""); const form = new FormData(event.currentTarget);
    try { await apiFetch("/api/clients", { method: "POST", body: JSON.stringify({ businessName: form.get("businessName"), sector: form.get("sector"), contact: { name: form.get("contactName"), email: form.get("email"), phone: form.get("phone") } }) }); setShowForm(false); event.currentTarget.reset(); load(); } catch (cause) { setFormError(cause instanceof ApiError ? cause.message : "Client gagal disimpan"); } finally { setSaving(false); }
  }
  async function importClients(file: File) { const form = new FormData(); form.append("file", file); const response = await fetch("/api/clients/import", { method: "POST", body: form }); const payload = await response.json().catch(() => ({})); if (!response.ok) return setError(payload.error ?? "Import CSV gagal"); setError(""); load(); }

  return <div className="ops-page page-enter"><PageHeader eyebrow="Relasi kerja" title="Client" description="Data client yang tampil mengikuti scope dan role akun yang sedang login." action={() => { setFormError(""); setShowForm(true); }} actionLabel="Tambah client" />
    <div className="mb-4 flex flex-wrap gap-2"><a href="/api/export?resource=clients" className="button button-quiet">Export CSV</a><a href="/api/export?resource=clients&format=excel" className="button button-quiet">Export Excel</a><label className="button button-quiet">Import CSV<input type="file" accept=".csv,text/csv" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importClients(file); event.currentTarget.value = ""; }} /></label></div>
    <section className="surface mt-6 p-4 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><SearchField value={query} onChange={setQuery} placeholder="Cari nama usaha, sektor, atau kontak…" /><div className="flex gap-2 overflow-x-auto">{([["Semua", "Semua"], ["ACTIVE", "Aktif"], ["PROSPECT", "Prospek"], ["INACTIVE", "Tidak aktif"], ["ARCHIVED", "Arsip"]] as const).map(([value, label]) => <button key={value} type="button" onClick={() => setStatus(value)} className={`min-h-10 whitespace-nowrap rounded-xl px-3 text-xs font-semibold transition ${status === value ? "bg-[#506545] text-white" : "border border-[var(--border)] text-[var(--muted)] hover:bg-[#eef3ec] hover:text-[#506545]"}`}>{label}</button>)}</div></div>{loading ? <div className="grid min-h-[260px] place-items-center"><p className="text-sm text-[var(--muted)]">Memuat client…</p></div> : error ? <div className="mt-5"><EmptyState icon="users" title="Client gagal dimuat" description={error} actionLabel="Coba lagi" onAction={load} /></div> : filtered.length === 0 ? <div className="mt-5"><EmptyState icon="users" title="Belum ada client yang cocok" description="Ubah pencarian atau buat client baru untuk memulai pendampingan." actionLabel="Tambah client" onAction={() => setShowForm(true)} /></div> : <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((client) => <Link href={`/dashboard/clients/${client.id}`} key={client.id} className="group rounded-2xl border border-[var(--border)] bg-white p-5 transition hover:-translate-y-0.5 hover:border-[#b8c8b1] hover:shadow-[0_8px_24px_rgba(35,57,38,0.06)]"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate text-base font-semibold text-[#334035] group-hover:text-[#506545]">{client.businessName}</h2><p className="mt-1 text-xs text-[var(--muted)]">{client.sector || "Sektor belum diisi"}</p></div><Badge tone={tone[client.status]} dot>{labels[client.status]}</Badge></div><div className="mt-5 border-t border-[var(--border)] pt-4"><p className="text-xs text-[var(--muted)]">Program</p><p className="mt-1 text-sm font-medium text-[#4b584d]">{client.programs.length ? client.programs[0].name : "Belum ada program"}</p><div className="mt-3 flex items-center justify-between text-xs"><span className="text-[var(--muted)]">Kontak: {client.contacts[0]?.name ?? "—"}</span><span className="text-[#506545]">Diperbarui {formatDate(client.updatedAt)}</span></div></div></Link>)}</div>}</section>
    {showForm && <div className="fixed inset-0 z-50 grid place-items-center bg-[#283529]/30 p-4 backdrop-blur-[2px]" role="dialog" aria-modal="true"><div className="w-full max-w-lg rounded-2xl border border-[var(--border)] bg-white p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between"><div><p className="eyebrow">Client baru</p><h2 className="mt-1 text-xl font-semibold tracking-[-0.03em] text-[#334035]">Tambahkan client</h2></div><button type="button" onClick={() => setShowForm(false)} className="grid h-9 w-9 place-items-center rounded-lg text-[var(--muted)] hover:bg-[#f0f2f0]" aria-label="Tutup">×</button></div><form className="mt-6 grid gap-4" onSubmit={createClient}><FormField label="Nama usaha"><input name="businessName" className={inputClass} required maxLength={160} placeholder="Contoh: Kedai Senja" /></FormField><FormField label="Sektor"><input name="sector" className={inputClass} maxLength={120} placeholder="Contoh: F&B" /></FormField><div className="border-t border-[var(--border)] pt-4"><p className="text-sm font-semibold text-[#334035]">Kontak utama</p><div className="mt-3 grid gap-4"><FormField label="Nama kontak"><input name="contactName" className={inputClass} required maxLength={160} placeholder="Nama pemilik atau PIC" /></FormField><div className="grid gap-4 sm:grid-cols-2"><FormField label="Email"><input name="email" type="email" className={inputClass} placeholder="nama@usaha.id" /></FormField><FormField label="Telepon"><input name="phone" className={inputClass} placeholder="08…" /></FormField></div></div></div>{formError && <p className="rounded-xl bg-[#fae9e7] p-3 text-xs font-medium text-[#a5423a]" role="alert">{formError}</p>}<div className="mt-2 flex justify-end gap-2"><button type="button" onClick={() => setShowForm(false)} className="min-h-11 rounded-xl px-4 text-sm font-semibold text-[var(--muted)] hover:bg-[#f0f2f0]">Batal</button><button disabled={saving} type="submit" className="min-h-11 rounded-xl bg-[#bf6d4e] px-4 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-60">{saving ? "Menyimpan…" : "Simpan client"}</button></div></form></div></div>}
  </div>;
}
